/*
 * Copyright 2022-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ktorm.ksp.api

/**
 * Specify the mapped column for an entity property, and bind this column to a reference table. Typically,
 * this column is a foreign key in relational databases. Entity sequence APIs would automatically left-join
 * all references (recursively) by default.
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.SOURCE)
public annotation class References(

    /**
     * The name of the column.
     *
     * If not specified, the default name will be generated by a naming strategy, which by default generates snake-case
     * names.
     */
    val name: String = "",

    /**
     * The name of the corresponding column property in the generated table object.
     *
     * If not specified, the default value will be the annotated property's name.
     */
    val propertyName: String = "",
)
