/*
 * Copyright 2022-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ktorm.ksp.api

/**
 * Specify the table for an entity class.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
public annotation class Table(

    /**
     * The name of the table.
     *
     * If not specified, the default name will be generated by a naming strategy, which by default generates snake-case
     * names.
     */
    val name: String = "",

    /**
     * The alias of the table.
     */
    val alias: String = "",

    /**
     * The catalog of the table.
     */
    val catalog: String = "",

    /**
     * The schema of the table.
     */
    val schema: String = "",

    /**
     * The name of the corresponding table class in the generated code.
     *
     * If not specified, the default value will be the plural form of the annotated class's name.
     */
    val className: String = "",

    /**
     * The name of the corresponding entity sequence in the generated code.
     *
     * If not specified, the default value will be the same as [className], with the first letter in lower-case.
     */
    val entitySequenceName: String = "",

    /**
     * Specify properties that should be ignored for generating column definitions.
     */
    val ignoreProperties: Array<String> = []
)
