package org.ktorm.ksp.compiler.generator

import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.squareup.kotlinpoet.FileSpec
import org.ktorm.ksp.spi.ExtCodeGenerator
import org.ktorm.ksp.spi.TableMetadata
import java.util.*

object FileGenerator {

    fun generate(table: TableMetadata, environment: SymbolProcessorEnvironment): FileSpec {
        val fileSpec = FileSpec.builder(table.entityClass.packageName.asString(), table.tableClassName)
            .addFileComment("Auto-generated by ktorm-ksp-compiler, DO NOT EDIT!")
            .addType(TableClassGenerator.generate(table, environment))
            .addProperty(EntitySequencePropertyGenerator.generate(table))

        if (table.entityClass.classKind == ClassKind.INTERFACE) {
            fileSpec.addFunction(PseudoConstructorFunctionGenerator.generate(table))
            fileSpec.addFunction(CopyFunctionGenerator.generate(table))

            for (func in ComponentFunctionGenerator.generate(table)) {
                fileSpec.addFunction(func)
            }
        } else {

        }

        for (generator in ServiceLoader.load(ExtCodeGenerator::class.java)) {
            // TODO: log generator info.

            for (type in generator.generateTypes(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addType(type)
            }

            for (property in generator.generateProperties(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addProperty(property)
            }

            for (function in generator.generateFunctions(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addFunction(function)
            }
        }

        return fileSpec.build()
    }
}