/*
 * Copyright 2022-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ktorm.ksp.compiler.generator

import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import org.ktorm.ksp.spi.ExtCodeGenerator
import org.ktorm.ksp.spi.TableMetadata
import java.util.*

object FileGenerator {

    fun generate(table: TableMetadata, environment: SymbolProcessorEnvironment): FileSpec {
        val fileSpec = FileSpec.builder(table.entityClass.packageName.asString(), table.tableClassName)
            .addFileComment("Auto-generated by ktorm-ksp-compiler, DO NOT EDIT!")
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class).addMember("%S", "RedundantVisibilityModifier").build())
            .addType(TableClassGenerator.generate(table, environment))
            .addProperty(EntitySequencePropertyGenerator.generate(table))

        if (table.entityClass.classKind == ClassKind.INTERFACE) {
            fileSpec.addFunction(PseudoConstructorFunctionGenerator.generate(table))
            fileSpec.addFunction(CopyFunctionGenerator.generate(table))

            for (func in ComponentFunctionGenerator.generate(table)) {
                fileSpec.addFunction(func)
            }
        } else {
            fileSpec.addFunction(AddFunctionGenerator.generate(table))

            if (table.columns.any { it.isPrimaryKey }) {
                fileSpec.addFunction(UpdateFunctionGenerator.generate(table))
            }
        }

        for (generator in ServiceLoader.load(ExtCodeGenerator::class.java)) {
            // TODO: log generator info.

            for (type in generator.generateTypes(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addType(type)
            }

            for (property in generator.generateProperties(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addProperty(property)
            }

            for (function in generator.generateFunctions(table, environment)) {
                // TODO: modify kdoc
                fileSpec.addFunction(function)
            }
        }

        return fileSpec.build()
    }
}
